export const FETCH_PATIENTS_START = 'FETCH_PATIENTS_START';
export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_ERROR = 'FETCH_PATIENTS_ERROR';

export const SAVE_PATIENT_START = 'SAVE_PATIENT_START';
export const SAVE_PATIENT_SUCCESS = 'SAVE_PATIENT_SUCCESS';
export const SAVE_PATIENT_ERROR = 'SAVE_PATIENT_ERROR';

export const PATIENT_DELETED = 'PATIENT_DELETED';
