dist: precise
language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
before_script:
  - yarn global add firebase-tools
install: yarn
script: yarn run build
after_success:
  - cd functions && npm install && firebase deploy --token=${FIREBASE_API_TOKEN}
branches:
  only:
  - master
