export const USER_NAME_MIN_LENGTH = 3;
export const USER_PASSWORD_MIN_LENGTH = 8;

export const USER_NAME_REQUIRED_ERROR_ID = 'USER_NAME_REQUIRED_ERROR_ID';
export const USER_NAME_MIN_LENGTH_ERROR_ID = 'USER_NAME_MIN_LENGTH_ERROR_ID';
export const USER_EMAIL_REQUIRED_ERROR_ID = 'USER_EMAIL_REQUIRED_ERROR_ID';
export const USER_EMAIL_INCORRECT_ERROR_ID = 'USER_EMAIL_INCORRECT_ERROR_ID';
export const USER_PASSWORD_REQUIRED_ERROR_ID = 'USER_PASSWORD_REQUIRED_ERROR_ID';
export const USER_PASSWORD_MIN_LENGTH_ERROR_ID = 'USER_PASSWORD_MIN_LENGTH_ERROR_ID';
export const USER_CONFIRMATION_PASSWORD_MUST_MATCH_ERROR_ID = 'USER_CONFIRMATION_PASSWORD_MUST_MATCH_ERROR_ID';
