const FETCH_TEAM = 'FETCH_TEAM';

export const FETCH_TEAM_START = `${FETCH_TEAM}_START`;
export const FETCH_TEAM_SUCCESS = `${FETCH_TEAM}_SUCCESS`;
export const FETCH_TEAM_ERROR = `${FETCH_TEAM}_ERROR`;

const SAVE_TEAM = 'SAVE_TEAM';

export const SAVE_TEAM_START = `${SAVE_TEAM}_START`;
export const SAVE_TEAM_SUCCESS = `${SAVE_TEAM}_SUCCESS`;
export const SAVE_TEAM_ERROR = `${SAVE_TEAM}_ERROR`;

export const EDIT_TEAM_PROFILE = 'EDIT_TEAM_PROFILE';

export const UPDATE_CAPTAIN_DATA = 'UPDATE_CAPTAIN_DATA';

export const ADD_ROSTER_MEMBER = 'ADD_ROSTER_MEMBER';
export const REMOVE_ROSTER_MEMBER = 'REMOVE_ROSTER_MEMBER';

export const CHANGE_TEAM_TITLE = 'CHANGE_TEAM_TITLE';

export const CREATE_TEAM = 'CREATE_TEAM';

const VERIFY_PHONE = 'VERIFY_PHONE';

export const VERIFY_PHONE_START = `${VERIFY_PHONE}_START`;
export const VERIFY_PHONE_SUCCESS = `${VERIFY_PHONE}_SUCCESS`;
export const VERIFY_PHONE_CONFIRM_SUCCESS = `${VERIFY_PHONE}_CONFIRM_SUCCESS`;
export const VERIFY_PHONE_ERROR = `${VERIFY_PHONE}_ERROR`;

const FETCH_USER = 'FETCH_USER';

export const FETCH_USER_START = `${FETCH_USER}_START`;
export const FETCH_USER_SUCCESS = `${FETCH_USER}_SUCCESS`;
export const FETCH_USER_ERROR = `${FETCH_USER}_ERROR`;

const SAVE_USER = 'SAVE_USER';

export const SAVE_USER_START = `${SAVE_USER}_START`;
export const SAVE_USER_SUCCESS = `${SAVE_USER}_SUCCESS`;
export const SAVE_USER_ERROR = `${SAVE_USER}_ERROR`;

export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';

const FETCH_TEAM_GAME_DATA = 'FETCH_TEAM_GAME_DATA';

export const FETCH_TEAM_GAME_DATA_START = `${FETCH_TEAM_GAME_DATA}_START`;
export const FETCH_TEAM_GAME_DATA_SUCCESS = `${FETCH_TEAM_GAME_DATA}_SUCCESS`;
export const FETCH_TEAM_GAME_DATA_ERROR = `${FETCH_TEAM_GAME_DATA}_ERROR`;

export const TEAM_JOIN_GAME_TOGGLED = 'TEAM_JOIN_GAME_TOGGLED';
