export const FETCH_SENSOR_SCHEMA_START = 'FETCH_SENSOR_SCHEMA_START';
export const FETCH_SENSOR_SCHEMA_SUCCESS = 'FETCH_SENSOR_SCHEMA_SUCCESS';
export const FETCH_SENSOR_SCHEMA_ERROR = 'FETCH_SENSOR_SCHEMA_ERROR';

export const STORE_SENSOR_SCHEMA_START = 'STORE_SENSOR_SCHEMA_START';
export const STORE_SENSOR_SCHEMA_SUCCESS = 'STORE_SENSOR_SCHEMA_SUCCESS';
export const STORE_SENSOR_SCHEMA_ERROR = 'STORE_SENSOR_SCHEMA_ERROR';
