export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED';

export const NOTIFICATION_PERMISSION_CHANGED = 'NOTIFICATION_PERMISSION_CHANGED';

export const NOTIFICATIONS_FETCHED = 'NOTIFICATIONS_FETCHED';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
